#include <stdio.h>

extern int yylex();  // Function generated by Flex

int yyparse();       // Function generated by Bison

void yyerror(const char* s) {
    fprintf(stderr, "Parser error: %s\n", s);
}

int main() {
    yyparse();
    return 0;
}